spring:
  profiles:
    active:
      - dev
---
spring:
    profiles: dev
    application:
      name: microservicecloud-config-sst-dev
---
spring:
    profiles: test
    application:
      name: microservicecloud-config-sst-test